// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by tool/privacy_policy_codegen.dart.

class PrivacyPolicySection {
  const PrivacyPolicySection({
    required this.id,
    required this.title,
    required this.paragraphs,
  });

  final String id;
  final String title;
  final List<String> paragraphs;
}

class PrivacyPolicyDocument {
  const PrivacyPolicyDocument({
    required this.title,
    required this.revision,
    required this.summary,
    required this.updatedDate,
    required this.sections,
  });

  static const current = PrivacyPolicyDocument(
    title: "MyCHU 用户协议",
    revision: "1.0.0-260925",
    summary: "账号密码在登录后安全保存在设备上；应用远程服务可在设置中关闭。",
    updatedDate: "2026-09-25",
    sections: <PrivacyPolicySection>[
      PrivacyPolicySection(
        id: "about",
        title: "一、关于本应用",
        paragraphs: <String>[
          "本应用的开发者是Rinn，您可以通过电子邮件：mychu.dev@rinn.moe联系开发者。",
          "**MyCHU 不是长安大学的官方应用，也不代表长安大学发布或运营。若因使用本应用造成的损失，开发者概不负责。**",
          "随着学校系统和 MyCHU 自身功能变化，本应用可能增加、调整或停止部分功能。",
        ],
      ),
      PrivacyPolicySection(
        id: "data_privacy",
        title: "二、数据与隐私",
        paragraphs: <String>[
          "为了在登录状态失效后实现自动恢复登录功能，当您在 MyCHU 中完成登录后，**账号及密码将以安全方式保存在您的设备上。**您应当仅使用本人拥有或已经获得合法授权的校园账号。",
          "您可以随时移除账号。移除后，在本机保存的登录凭据及相关登录状态将会被删除。",
          "本应用存在托管的服务端，用于及时发布信息、匿名统计等帮助改善本应用的目的。统计功能不会收集您的任何账号密码、学号、课程、成绩等信息。您可以在设置中关闭此功能。",
        ],
      ),
      PrivacyPolicySection(
        id: "system_permissions",
        title: "四、系统权限的使用",
        paragraphs: <String>[
          "MyCHU 会根据功能需要申请通知、定位、摄像头、麦克风等系统权限，由您自由决定授予。",
          "相关权限仅在对应功能需要时使用。您可以通过系统设置管理这些权限，拒绝或关闭某项权限可能导致对应功能无法正常使用。",
        ],
      ),
      PrivacyPolicySection(
        id: "agreement_changes",
        title: "五、协议变更",
        paragraphs: <String>[
          "MyCHU 可能根据功能和服务变化更新本协议。",
          "您可以随时在应用中查看当前版本。继续使用更新后的 MyCHU，即表示您接受更新后的协议；对于依法需要重新取得同意的事项，MyCHU 将另行向您请求确认。",
        ],
      ),
    ],
  );

  final String title;
  final String revision;
  final String summary;
  final String updatedDate;
  final List<PrivacyPolicySection> sections;
}
